name: leveldb
description: Dart bindings for the LevelDB key value store. LevelDB is a fast key/value data store which
  supports arbitrary byte arrays as both keys and values.
version: 7.0.0
homepage: https://github.com/adamlofts/leveldb_dart
environment:
  sdk: '>=2.12.0 <2.15.0'

dependencies:
  meta: ^1.1.6
dev_dependencies:
  test: '>=1.3.0 <=1.17.0'
